 b module.exports = [
  { "id": 1, "fact": "HTML is for content.", "by": "https://github.com/denisecase" },
  { "id": 2, "fact": "CSS is for style.", "by": "https://github.com/denisecase" },
  { "id": 3, "fact": "JavaScript is for logic.", "by": "https://github.com/denisecase" },
  { "id": 4, "fact": "TCP/IP was invented by Vint Cerf and Bob Kahn in 1974", "by": "https://github.com/mprogers" },
  { "id": 5, "fact": "Server-side apps can be written in numerous languages, including Java, JavaScript, Perl, PHP, Python, and, most recently, Swift", "by": "https://github.com/mprogers" },
  { "id": 6, "fact": "Node.js, invented by Ryan Dahl in 2009, originally ran only on Linux and macOS", "by": "https://github.com/mprogers" },
  { "id": 7, "fact": "A web application is a software application that runs on a remote server.", "by": "https://github.com/nandinidoppalapudi" },
  { "id": 8, "fact": "Nodejs is single threaded.", "by":"https://github.com/rahulreddy062"},
  { "id": 9, "fact": "Web server can refer to hardware or software, or both of them working together.", "by": "https://github.com/karanamvijaykumar" },
  { "id": 23, "fact": "Java and JavaScript are not the same language.", "by":"https://github.com/JosephCW" },
  { "id": 101},
  { "id": 102, "fact": " a world wide web is an information space.", "by": "https://github.com/Rethima-Reddy"},
  { "id": 103},
  { "id": 104,"fact": "Express is a framework for Node.js","by":"https://github.com/rohan6471"},
  { "id": 105, "fact": "PWA stands for Progressive Web App.", "by": "https://github.com/Logan11999"},
  { "id": 106},
  { "id": 107, "fact": "A Web server is a computer system that processes requests via HTTP to distribute information on the WWW.", "by": "https://github.com/AshleyStanbridge96"},
  { "id": 106, "fact": "Screen size affects the look of a website.", "by": "https://github.com/tjac1336"},
  { "id": 107},
  { "id": 109, "fact": "HTML is the standard markup language for Web pages.", "by": "https://github.com/Kamal4195"},
  { "id": 108, "fact": "Progressive Web Apps fit any screen size and can be used without a network connection.", "by": "https://github.com/kdibben" },
  { "id": 110},
  { "id": 111,"fact": "JavaScript is a scripting language,primarily used on web", "by": "https://github.com/Dheeraj0327"},
  { "id": 112},

  { "id": 113,"fact": "My github account.", "by": "https://github.com/jeevanreddymure"},
  { "id": 114},
  { "id": 113},
  { "id": 115,"fact": "Flask is a microframework for Python","by":"https://github.com/AlekyaPochampally"},

  { "id": 114}, "fact": "HTML is hyper text markup language use to create web pages", "by": "https://github.com/AzharAlali"},
 
  { "id": 116},
  { "id": 117, "fact": "Javascript is single threaded, but web workers and event listeners can be utilized to run javascript in a seperate background thread.", "by": "https://github.com/dakotagrvtt" },
  { "id": 118, "fact": "PWA stands for Progressive Web Appplication.", "by": "https://github.com/jfolkerts"},
  { "id": 119, "fact": "HTML stands for HyperText Markup Language", "by": "https://github.com/s534141"},
  { "id": 120},
  { "id": 121, "fact": "The CSS font-style property accepts a value of oblique aside from normal or italic.", "by": "https://github.com/cweltonsmith"},
  { "id": 122, "fact": "Python Flask is a back end web development tool that uses python.", "by": "https://github.com/khart0012"},
  { "id": 123},
  { "id": 124},
  { "id": 201, "fact": "React is a widely used libaray.","by": "https://github.com/xchen182"},
  { "id": 202, "fact": "Working in the same project as other people can be messy", "by": "https://github.com/DCoop25"},
  { "id": 203, "fact": "JSON stores data in key-value pairs.", "by": "https://github.com/terry-woosley"},
  { "id": 204, "fact": "JavaScript is not a part of Java programming", "by": "https://github.com/prasadbobbilla"},
  { "id": 205, "fact": "java slogan Write once run anywhere", "by": "https://github.com/naveenpi"},
  { "id": 206, "fact": "WWW stands for World Wide Web", "by": "https://github.com/ayhalali" },
  { "id": 207, "fact":"Vue.js is an open-source Model–view–viewmodel JavaScript framework for building user interfaces and single-page applications.", "by": "https://github.com/anil-bomma" },
  { "id": 208, "fact": "HTTPS works on port 443 and HTTP works on port 80", "by": "https://github.com/bharat-reddy-male"},
  { "id": 209, "fact": "React is a framework.", "by": "https://github.com/yugimamidi"},
  { "id": 210, "fact": "React is a java script library maintained by facebook and some other individual members.", "by": "https://github.com/abhiteja29" },
  { "id": 211, "fact": "JSON stands for JavaScript Object Notation", "by": "https://github.com/Echtniet"},
  { "id": 212, "fact": "In Javascript, an Array plus an Object equals an array of objects. An object plus an array equals 0.", "by": "https://github.com/mtburnes"},
  { "id": 213},
  { "id": 214, "fact": "The average lifespan of a website is 3 years", "by": "https://github.com/JacobTaylorNWMSU"},
  { "id": 215},
  { "id": 216, "fact": "Flask is a microweb Framework written in python", "by": "https://github.com/hareeshbhuma"},
  { "id": 217 , "fact":"Angular is a TypeScript-based open-source web application framework led by the Angular Team at Google.", "by":"https://github.com/RaghunandanKumar"},
  { "id": 218, "fact": "Express framework is built on top of the node.js framework", "by":"https://github.com/Bhavya-123"}
  { "id": 219, "fact": "Angular is a platform for building mobile and desktop web applications.", "by": "https://github.com/prudhvi15"},
  { "id": 220, "fact": "PWA (Progressive Web App) is a responsive web app.", "by": "https://github.com/tanibi"},
  { "id": 221, "fact": "React is not a framework. It is a JavaScript library", "by": "https://github.com/aawajjoshi" },
  { "id": 222, "fact":"Progressive Web Apps are the recent innovation in technology. PWAs are an escape from the App Store.", "by":"https://github.com/suma-gitrep"},
  { "id": 223, "fact": "GitHub is a opensource version control system to store the code.", "by": "https://github.com/mohanpratapa" },
  { "id": 224},
  { "id": 401},
  { "id": 402},
  { "id": 403},
  { "id": 404},
  { "id": 405},
  { "id": 406},
  { "id": 407},
  { "id": 408},
  { "id": 409},
  { "id": 410},
  { "id": 411},
  { "id": 412},
  { "id": 413},
  { "id": 414},
  { "id": 415},
  { "id": 416},
  { "id": 417},
  { "id": 418},
  { "id": 419},
  { "id": 420},
  { "id": 421},
  { "id": 422},
  { "id": 423},
  { "id": 424},
]
